- hosts: fe1:fe2
  tasks:
          - name: build docker frontend
            command: "chdir=/home/{{ansible_user}}/literature-frontend docker build -t anjardanis/literature-frontend ."
            become_user: "{{ansible_user}}"

          - name: run literature-frontend
            command: "chdir=/home/{{ansible_user}}/literature-frontend docker-compose up -d"
            become_user: "{{ansible_user}}"

- hosts: be1:be2
  tasks:
          - name: build docker backend
            command: "chdir=/home/{{ansible_user}}/literature-backend docker build -t anjardanis/literature-backend ."               
            become_user: "{{ansible_user}}"

          - name: run literature-backend
            command: "chdir=/home/{{ansible_user}}/literature-backend docker-compose up -d"
            become_user: "{{ansible_user}}"
