- hosts: nginx
  tasks:
  - name: Ansible copy directory to public server
    become_user: "{{ansible_user}}"
    copy:
      src: nginx
      dest: "/home/{{ansible_user}}/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 755

- hosts: mn
  tasks:
  - name: Ansible copy directory to monitoring server
    become_user: "{{ansible_user}}"
    copy:
      src: grafana
      dest: "/home/{{ansible_user}}/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 755

  - name: Ansible copy directory to monitoring server
    become_user: "{{ansible_user}}"
    copy:
      src: prometheus
      dest: "/home/{{ansible_user}}/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 755
