- hosts: fe1:fe2:be1:be2:db1:db2:cicd:public
  tasks:
          - name: "create users monitoring except monitoring server"
            user:
                    name: monitoring
                    password: "$6$CjI1u8z2chKyEka$ka/CR75ySm.Dchny13kVH6UTFu1jJZsUM9HZnCAQWkiJIgEcgDSjgxGA97Wai5P76AxGf9C9s/O.N/vr2r7gm0"
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/monitoring
