- hosts: cicd
  tasks:
          - name: run jenkins
            command: docker run --name cicd -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/usr/app jenkins/jenkins:lts
            become_user: "{{ansible_user}}"
